/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _R_H_RPCGEN
#define _R_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct query_msg {
	char *msg;
	char *md5;
};
typedef struct query_msg query_msg;

struct store_1_argument {
	char *sender;
	char *receiver;
	int id;
	char *text;
	char *md5;
	char *path;
};
typedef struct store_1_argument store_1_argument;

struct query_1_argument {
	char *user;
	char *arg2;
};
typedef struct query_1_argument query_1_argument;

#define MESSAGE_SERVER 0x23456788
#define MESSAGE_SERVER_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define INIT 1
extern  int * init_1(CLIENT *);
extern  int * init_1_svc(struct svc_req *);
#define REGISTER 2
extern  int * register_1(char *, CLIENT *);
extern  int * register_1_svc(char *, struct svc_req *);
#define UNREGISTER 3
extern  int * unregister_1(char *, CLIENT *);
extern  int * unregister_1_svc(char *, struct svc_req *);
#define STORE 4
extern  int * store_1(char *, char *, int , char *, char *, char *, CLIENT *);
extern  int * store_1_svc(char *, char *, int , char *, char *, char *, struct svc_req *);
#define MSG_COUNT 5
extern  int * msg_count_1(char *, CLIENT *);
extern  int * msg_count_1_svc(char *, struct svc_req *);
#define QUERY 6
extern  query_msg * query_1(char *, char *, CLIENT *);
extern  query_msg * query_1_svc(char *, char *, struct svc_req *);
extern int message_server_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define INIT 1
extern  int * init_1();
extern  int * init_1_svc();
#define REGISTER 2
extern  int * register_1();
extern  int * register_1_svc();
#define UNREGISTER 3
extern  int * unregister_1();
extern  int * unregister_1_svc();
#define STORE 4
extern  int * store_1();
extern  int * store_1_svc();
#define MSG_COUNT 5
extern  int * msg_count_1();
extern  int * msg_count_1_svc();
#define QUERY 6
extern  query_msg * query_1();
extern  query_msg * query_1_svc();
extern int message_server_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_query_msg (XDR *, query_msg*);
extern  bool_t xdr_store_1_argument (XDR *, store_1_argument*);
extern  bool_t xdr_query_1_argument (XDR *, query_1_argument*);

#else /* K&R C */
extern bool_t xdr_query_msg ();
extern bool_t xdr_store_1_argument ();
extern bool_t xdr_query_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_R_H_RPCGEN */
