/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "r.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

int *
init_1(CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	 if (clnt_call (clnt, INIT, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
register_1(char *user,  CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, REGISTER,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &user,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
unregister_1(char *user,  CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, UNREGISTER,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &user,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
store_1(char *sender, char *receiver, int id, char *text, char *md5, char *path,  CLIENT *clnt)
{
	store_1_argument arg;
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.sender = sender;
	arg.receiver = receiver;
	arg.id = id;
	arg.text = text;
	arg.md5 = md5;
	arg.path = path;
	if (clnt_call (clnt, STORE, (xdrproc_t) xdr_store_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
msg_count_1(char *user,  CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, MSG_COUNT,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &user,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

query_msg *
query_1(char *user, char *arg2,  CLIENT *clnt)
{
	query_1_argument arg;
	static query_msg clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.user = user;
	arg.arg2 = arg2;
	if (clnt_call (clnt, QUERY, (xdrproc_t) xdr_query_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_query_msg, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
