/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "r.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static int *
_init_1 (void  *argp, struct svc_req *rqstp)
{
	return (init_1_svc(rqstp));
}

static int *
_register_1 (char * *argp, struct svc_req *rqstp)
{
	return (register_1_svc(*argp, rqstp));
}

static int *
_unregister_1 (char * *argp, struct svc_req *rqstp)
{
	return (unregister_1_svc(*argp, rqstp));
}

static int *
_store_1 (store_1_argument *argp, struct svc_req *rqstp)
{
	return (store_1_svc(argp->sender, argp->receiver, argp->id, argp->text, argp->md5, argp->path, rqstp));
}

static int *
_msg_count_1 (char * *argp, struct svc_req *rqstp)
{
	return (msg_count_1_svc(*argp, rqstp));
}

static query_msg *
_query_1 (query_1_argument *argp, struct svc_req *rqstp)
{
	return (query_1_svc(argp->user, argp->arg2, rqstp));
}

static void
message_server_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		char *register_1_arg;
		char *unregister_1_arg;
		store_1_argument store_1_arg;
		char *msg_count_1_arg;
		query_1_argument query_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case INIT:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _init_1;
		break;

	case REGISTER:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _register_1;
		break;

	case UNREGISTER:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _unregister_1;
		break;

	case STORE:
		_xdr_argument = (xdrproc_t) xdr_store_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _store_1;
		break;

	case MSG_COUNT:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _msg_count_1;
		break;

	case QUERY:
		_xdr_argument = (xdrproc_t) xdr_query_1_argument;
		_xdr_result = (xdrproc_t) xdr_query_msg;
		local = (char *(*)(char *, struct svc_req *)) _query_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (MESSAGE_SERVER, MESSAGE_SERVER_VERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, MESSAGE_SERVER, MESSAGE_SERVER_VERS, message_server_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (MESSAGE_SERVER, MESSAGE_SERVER_VERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, MESSAGE_SERVER, MESSAGE_SERVER_VERS, message_server_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (MESSAGE_SERVER, MESSAGE_SERVER_VERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
