/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "r.h"

bool_t
xdr_query_msg (XDR *xdrs, query_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->msg, 255))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->md5, 255))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_store_1_argument (XDR *xdrs, store_1_argument *objp)
{
	 if (!xdr_string (xdrs, &objp->sender, 255))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->receiver, 255))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->text, 255))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->md5, 255))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->path, 255))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_query_1_argument (XDR *xdrs, query_1_argument *objp)
{
	 if (!xdr_string (xdrs, &objp->user, 255))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->arg2, 255))
		 return FALSE;
	return TRUE;
}
